import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';

const CHANNELS=['Markets','Tech','Crypto','World','Gadgets'];
const configured=Boolean(SUPABASE_URL&&SUPABASE_ANON_KEY);
const supabase=configured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const AUTH_REDIRECT_URL=new URL('./',window.location.href).href.split('#')[0].split('?')[0];
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
let currentUser=null,currentProfile=null,isAdmin=false,activeChannel='Hub',calls=[],threads=[],myPositions=[],comments=[],selectedCall=null,selectedSide='YES',authMode='signin';

const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),3200)};
const openModal=id=>document.getElementById(id).showModal();
const fmtDate=v=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00`));
const ago=v=>{const m=Math.max(0,Math.floor((Date.now()-new Date(v))/60000));return m<1?'now':m<60?`${m}m`:m<1440?`${Math.floor(m/60)}h`:`${Math.floor(m/1440)}d`};
const nameOf=c=>c?.profiles?.username||'member';
const statusOf=c=>c.status==='challenge'&&new Date(c.challenge_ends_at)<=new Date()?'open':c.status;
const pts=c=>(c.positions||[]).reduce((n,p)=>n+(p.points||0),0);
const scoreCall=c=>c.status==='resolved'&&typeof c.result==='boolean'?(c.result?100-c.confidence:-c.confidence):0;
const userStats=(username)=>{const own=calls.filter(c=>nameOf(c)===username),resolved=own.filter(c=>c.status==='resolved'&&typeof c.result==='boolean'),correct=resolved.filter(c=>c.result).length;return{own,resolved:resolved.length,accuracy:resolved.length?Math.round(correct/resolved.length*100):null,score:resolved.reduce((n,c)=>n+scoreCall(c),0),live:own.filter(c=>['challenge','open'].includes(statusOf(c))).length}};

function requireAccount(){if(!configured){toast('Supabase is not configured.');return false}if(!currentUser){openModal('authModal');return false}return true}
function populateChannels(){const opts=CHANNELS.map(x=>`<option>${x}</option>`).join('');$('#channelInput').innerHTML=opts;$('#threadChannelInput').innerHTML=opts;$('#channelNav').innerHTML=['Hub',...CHANNELS].map(x=>`<button class="channel ${x==='Hub'?'active':''}" data-channel="${x}">${x}</button>`).join('');renderRail()}
function renderRail(){ $('#railChannels').innerHTML=['Hub',...CHANNELS].map(c=>`<button class="rail-channel ${c===activeChannel?'active':''}" data-channel="${c}"><span>${c}</span><span>${calls.filter(x=>c==='Hub'||x.channel===c).length}</span></button>`).join('') }

async function boot(){populateChannels();if(!configured){$('#connectionBadge').textContent='Setup required';toast('Run Phase 3 setup first.');return}$('#connectionBadge').textContent='Live database';$('#connectionBadge').classList.add('live');const { error: openDueError } = await supabase.rpc('open_due_calls'); if (openDueError) console.warn('open_due_calls:', openDueError.message);const {data:{session}}=await supabase.auth.getSession();currentUser=session?.user||null;await loadProfile();await loadData();await checkAdmin();supabase.auth.onAuthStateChange(async(_e,s)=>{currentUser=s?.user||null;await loadProfile();await checkAdmin();await loadData()});handleHash()}
async function loadProfile(){currentProfile=null;if(currentUser){const {data}=await supabase.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();currentProfile=data||null}updateAccountUI()}
async function checkAdmin(){isAdmin=false;if(currentUser){const {data}=await supabase.rpc('is_admin');isAdmin=Boolean(data)}if($('#adminResolveBtn'))$('#adminResolveBtn').classList.toggle('hidden',!isAdmin)}
async function loadData(){
  const [cr,tr,allProfiles,allPositions,myPr]=await Promise.all([
    supabase.from('calls').select('*').order('created_at',{ascending:false}).limit(150),
    supabase.from('threads').select('*').order('created_at',{ascending:false}).limit(80),
    supabase.from('profiles').select('id,username'),
    supabase.from('positions').select('call_id,user_id,points,side'),
    currentUser?supabase.from('positions').select('*').eq('user_id',currentUser.id):Promise.resolve({data:[],error:null})
  ]);
  const firstError=[cr,tr,allProfiles,allPositions,myPr].find(x=>x?.error)?.error;
  if(firstError)toast(firstError.message);
  const profileMap=new Map((allProfiles.data||[]).map(p=>[String(p.id),p]));
  const positionsByCall=new Map();
  for(const p of (allPositions.data||[])){
    const k=String(p.call_id); if(!positionsByCall.has(k))positionsByCall.set(k,[]); positionsByCall.get(k).push(p);
  }
  calls=(cr.data||[]).map(c=>({...c,profiles:profileMap.get(String(c.author_id))||null,positions:positionsByCall.get(String(c.id))||[]}));
  threads=(tr.data||[]).map(t=>({...t,profiles:profileMap.get(String(t.author_id))||null}));
  myPositions=myPr.data||[];
  renderAll();
}
function updateAccountUI(){const on=!!currentUser;$('#authBtn').classList.toggle('hidden',on);$('#profileBtn').classList.toggle('hidden',!on);if(on)$('#profileBtn').textContent=(currentProfile?.username||currentUser.email||'?').slice(0,2).toUpperCase()}
function renderAll(){renderRail();renderCalls();renderThreads();renderStats();renderLeaderboard();renderResolving();$$('[data-channel]').forEach(b=>b.classList.toggle('active',b.dataset.channel===activeChannel))}
function filtered(list){return activeChannel==='Hub'?list:list.filter(x=>x.channel===activeChannel)}
function renderCalls(){let list=filtered([...calls]);const sort=$('#sortCalls').value;if(sort==='new')list.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));if(sort==='soon')list.sort((a,b)=>new Date(a.resolution_date)-new Date(b.resolution_date));if(sort==='confidence')list.sort((a,b)=>b.confidence-a.confidence);if(sort==='hot')list.sort((a,b)=>pts(b)-pts(a));$('#callsList').innerHTML=list.length?list.map(callCard).join(''):'<div class="empty-state"><strong>No calls here yet.</strong>Be the first to put a view on record.</div>'}
function callCard(c){const st=statusOf(c),mine=myPositions.find(p=>String(p.call_id)===String(c.id)),resultBadge=c.status==='resolved'?`<span class="badge ${c.result?'correct':'wrong'}">${c.result?'CORRECT':'WRONG'}</span>`:'';return `<article class="call-card clickable" data-open-call="${c.id}"><div class="call-top"><div class="badges"><span class="badge">${c.channel}</span><span class="badge ${st}">${st==='challenge'?'Wording challenge':st}</span>${resultBadge}</div><span class="call-meta-right">${c.confidence}% confidence</span></div><h3 class="call-title">${esc(c.claim)}</h3><div class="call-author"><span class="author-link" data-profile="${esc(nameOf(c))}">${esc(nameOf(c))}</span><span>·</span><span>${pts(c)} pts staked</span><span>·</span><span>resolves ${fmtDate(c.resolution_date)}</span></div><p class="call-condition">${esc(c.settlement_condition)}</p>${c.position_disclosure?`<p class="call-disclosure">Position disclosure: ${esc(c.position_disclosure)}</p>`:''}<div class="call-actions">${st==='open'?`<button class="side-button yes ${mine?.side==='YES'?'selected':''}" data-side="YES" data-call="${c.id}">YES</button><button class="side-button no ${mine?.side==='NO'?'selected':''}" data-side="NO" data-call="${c.id}">NO</button>`:`<span class="form-note">${st==='challenge'?'Open after the 24-hour wording challenge.':st==='resolved'?`Permanent result recorded. Score ${scoreCall(c)>=0?'+':''}${scoreCall(c)}.`:'This call is closed.'}</span>`}<span class="participants">${(c.positions||[]).length} member${(c.positions||[]).length===1?'':'s'} in</span></div></article>`}
function renderThreads(){const list=filtered(threads);$('#threadsList').innerHTML=list.length?list.map(t=>`<article class="thread-row"><div class="thread-title">${esc(t.title)}</div><div class="thread-body">${esc(t.body)}</div><div class="thread-meta">${t.channel} · <span class="author-link" data-profile="${esc(nameOf(t))}">${esc(nameOf(t))}</span> · ${ago(t.created_at)}</div></article>`).join(''):'<div class="empty-state"><strong>No discussion yet.</strong>Talk does not need to be a prediction.</div>'}
function renderStats(){if(!currentUser){$('#recordHeadline').textContent='Build a record worth showing.';['accuracyStat','scoreStat'].forEach(id=>$('#'+id).textContent=id==='scoreStat'?'0':'—');$('#resolvedStat').textContent='0';$('#openStat').textContent='0';$('#challengeDetail').textContent='0 in wording challenge';return}const s=userStats(currentProfile?.username||'');$('#recordHeadline').textContent=s.resolved?`${s.accuracy}% accurate · ${s.score>=0?'+':''}${s.score} score`:`${currentProfile?.username||'Your'} record starts here.`;$('#accuracyStat').textContent=s.accuracy===null?'—':`${s.accuracy}%`;$('#scoreStat').textContent=s.score>=0?`+${s.score}`:s.score;$('#resolvedStat').textContent=s.resolved;$('#openStat').textContent=s.live;$('#challengeDetail').textContent=`${s.own.filter(c=>statusOf(c)==='challenge').length} in wording challenge`}
function renderLeaderboard(){const names=[...new Set(calls.map(nameOf))],rows=names.map(n=>({name:n,...userStats(n)})).sort((a,b)=>b.score-a.score||b.accuracy-a.accuracy);$('#leaderboard').innerHTML=rows.length?rows.slice(0,10).map((r,i)=>`<div class="leader-row"><span>${i+1}</span><div class="leader-name" data-profile="${esc(r.name)}"><strong>${esc(r.name)}</strong><small>${r.accuracy===null?'No results':`${r.accuracy}% · ${r.resolved} resolved`}</small></div><span class="leader-score">${r.score>=0?'+':''}${r.score}</span></div>`).join(''):'<p class="form-note">No records yet.</p>'}
function renderResolving(){const list=calls.filter(c=>['challenge','open'].includes(statusOf(c))).sort((a,b)=>new Date(a.resolution_date)-new Date(b.resolution_date)).slice(0,6);$('#resolvingList').innerHTML=list.length?list.map(c=>`<div class="resolving-item" data-open-call="${c.id}"><div class="resolving-date">${fmtDate(c.resolution_date)}</div><div class="resolving-title">${esc(c.claim)}</div><div class="resolving-meta">${c.channel} · ${pts(c)} pts</div></div>`).join(''):'<p class="form-note">Nothing resolving soon.</p>'}
function setChannel(c){activeChannel=c;renderAll()}

async function openCall(id,push=true){selectedCall=calls.find(c=>String(c.id)===String(id));if(!selectedCall)return;$('#detailClaim').textContent=selectedCall.claim;const st=statusOf(selectedCall);$('#detailMeta').innerHTML=`<span class="badge">${selectedCall.channel}</span><span class="badge ${st}">${st}</span><span>${selectedCall.confidence}% confidence</span><span>by <b class="author-link" data-profile="${esc(nameOf(selectedCall))}">${esc(nameOf(selectedCall))}</b></span><span>resolves ${fmtDate(selectedCall.resolution_date)}</span><span>${esc(selectedCall.resolution_method||'source')} resolution</span>${selectedCall.source_name?`<span>source: ${esc(selectedCall.source_name)}</span>`:''}`;$('#detailCondition').textContent=selectedCall.settlement_condition;const rb=$('#detailResolution');if(selectedCall.status==='resolved'||selectedCall.status==='void'){rb.className=`resolution-box ${selectedCall.status==='resolved'?(selectedCall.result?'correct':'wrong'):''}`;rb.innerHTML=`<strong>${selectedCall.status==='void'?'VOID':selectedCall.result?'YES — correct':'NO — wrong'}</strong><p>${esc(selectedCall.resolution_note||'Result recorded.')}</p>${selectedCall.resolution_source_url?`<a href="${esc(selectedCall.resolution_source_url)}" target="_blank" rel="noopener">Resolution source ↗</a>`:''}`}else rb.className='resolution-box hidden';const mine=myPositions.find(p=>String(p.call_id)===String(selectedCall.id));$('#detailActions').innerHTML=st==='open'?`<button class="side-button yes ${mine?.side==='YES'?'selected':''}" data-side="YES" data-call="${selectedCall.id}">YES</button><button class="side-button no ${mine?.side==='NO'?'selected':''}" data-side="NO" data-call="${selectedCall.id}">NO</button><span class="form-note">${pts(selectedCall)} play points staked.</span>`:`<span class="form-note">${st==='challenge'?'Wording is still being challenged.':st==='resolved'?'This call is permanently resolved.':'This call is closed.'}</span>`;$('#flagCallBtn').classList.toggle('hidden',st!=='challenge');$('#adminResolveBtn').classList.toggle('hidden',!isAdmin||!['open','challenge'].includes(st));await loadComments(id);openModal('callDetailModal');if(push)history.replaceState(null,'',`#call-${id}`)}
async function loadComments(id){
  const {data,error}=await supabase.from('call_comments').select('*').eq('call_id',id).order('created_at',{ascending:true});
  if(error){$('#commentsList').innerHTML='<p class="form-note">Could not load discussion: '+esc(error.message)+'</p>';return}
  const authorIds=[...new Set((data||[]).map(c=>c.author_id).filter(Boolean))];
  let profileMap=new Map();
  if(authorIds.length){const {data:pdata}=await supabase.from('profiles').select('id,username').in('id',authorIds);profileMap=new Map((pdata||[]).map(p=>[String(p.id),p]));}
  comments=(data||[]).map(c=>({...c,profiles:profileMap.get(String(c.author_id))||null}));
  $('#commentsList').innerHTML=comments.length?comments.map(c=>`<div class="comment"><div class="comment-head"><span class="author-link" data-profile="${esc(c.profiles?.username||'member')}">${esc(c.profiles?.username||'member')}</span><span>${ago(c.created_at)}</span></div><div class="comment-body">${esc(c.body)}</div></div>`).join(''):'<p class="form-note">No comments yet. Start the discussion.</p>'
}
function openProfile(username,push=true){const s=userStats(username);$('#profileUsername').textContent=username;$('#profileAccuracy').textContent=s.accuracy===null?'—':`${s.accuracy}%`;$('#profileScore').textContent=s.score>=0?`+${s.score}`:s.score;$('#profileResolved').textContent=s.resolved;$('#profileOpen').textContent=s.live;$('#profileBreakdown').innerHTML=CHANNELS.map(ch=>{const r=s.own.filter(c=>c.channel===ch&&c.status==='resolved'),a=r.length?Math.round(r.filter(c=>c.result).length/r.length*100):null;return `<div class="breakdown-row"><span>${ch}</span><strong>${a===null?'—':a+'%'}</strong></div>`}).join('');$('#profileCalls').innerHTML=s.own.slice(0,8).map(c=>`<div class="mini-call" data-open-call="${c.id}"><strong>${esc(c.claim)}</strong><div class="thread-meta">${c.channel} · ${statusOf(c)}${c.status==='resolved'?` · ${scoreCall(c)>=0?'+':''}${scoreCall(c)} score`:''}</div></div>`).join('')||'<p class="form-note">No calls yet.</p>';$('#signOutBtn').classList.toggle('hidden',username!==(currentProfile?.username));openModal('profileModal');if(push)history.replaceState(null,'',`#profile-${encodeURIComponent(username)}`)}
function handleHash(){const h=location.hash;if(h.startsWith('#call-'))openCall(h.slice(6),false);else if(h.startsWith('#profile-'))openProfile(decodeURIComponent(h.slice(9)),false)}

$$('[data-close]').forEach(b=>b.addEventListener('click',()=>{document.getElementById(b.dataset.close).close();if(['callDetailModal','profileModal'].includes(b.dataset.close))history.replaceState(null,'',location.pathname)}));
$('#authBtn').addEventListener('click',()=>openModal('authModal'));$('#profileBtn').addEventListener('click',()=>openProfile(currentProfile?.username||currentUser?.email?.split('@')[0]));
$$('[data-auth-mode]').forEach(b=>b.addEventListener('click',()=>{authMode=b.dataset.authMode;$$('[data-auth-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#usernameLabel').classList.toggle('hidden',authMode!=='signup');$('#usernameInput').required=authMode==='signup';$('#authTitle').textContent=authMode==='signup'?'Create account':'Sign in';$('#authSubmitBtn').textContent=authMode==='signup'?'Create account':'Sign in'}));
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const email=$('#emailInput').value.trim(),password=$('#passwordInput').value;if(authMode==='signup'){const username=$('#usernameInput').value.trim();const {error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:AUTH_REDIRECT_URL,data:{username}}});if(error)return toast(error.message);toast('Account created. Check your email if confirmation is enabled.')}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)return toast(error.message);toast('Signed in.')}$('#authModal').close()});
$('#signOutBtn').addEventListener('click',async()=>{await supabase.auth.signOut();$('#profileModal').close();history.replaceState(null,'',location.pathname);toast('Signed out.')});
$('#newCallBtn').addEventListener('click',()=>{if(!requireAccount())return;const d=new Date();d.setDate(d.getDate()+7);$('#dateInput').min=new Date().toISOString().slice(0,10);$('#dateInput').value=d.toISOString().slice(0,10);openModal('callModal')});
$('#confidenceInput').addEventListener('input',e=>$('#confidenceValue').textContent=`${e.target.value}%`);
$('#callForm').addEventListener('submit',async e=>{e.preventDefault();if(!requireAccount())return;const payload={author_id:currentUser.id,channel:$('#channelInput').value,claim:$('#claimInput').value.trim(),settlement_condition:$('#conditionInput').value.trim(),confidence:Number($('#confidenceInput').value),resolution_date:$('#dateInput').value,position_disclosure:$('#disclosureInput').value.trim()||null,status:'challenge',resolution_method:$('#resolutionMethodInput').value,source_name:$('#sourceNameInput').value.trim()||null};const {error}=await supabase.from('calls').insert(payload);if(error)return toast(error.message);e.target.reset();$('#confidenceValue').textContent='70%';$('#callModal').close();toast('Call published into wording challenge.');await loadData()});
$('#newThreadBtn').addEventListener('click',()=>{if(requireAccount())openModal('threadModal')});$('#threadForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.from('threads').insert({author_id:currentUser.id,channel:$('#threadChannelInput').value,title:$('#threadTitleInput').value.trim(),body:$('#threadBodyInput').value.trim()});if(error)return toast(error.message);e.target.reset();$('#threadModal').close();toast('Thread posted.');await loadData()});
function positionClick(btn){if(!requireAccount())return;selectedCall=calls.find(c=>String(c.id)===String(btn.dataset.call));selectedSide=btn.dataset.side;$('#positionTitle').textContent=selectedSide;$('#positionClaim').textContent=selectedCall.claim;const mine=myPositions.find(p=>String(p.call_id)===String(selectedCall.id));$('#pointsInput').value=mine?.points||10;openModal('positionModal')}
$('#positionForm').addEventListener('submit',async e=>{e.preventDefault();const points=Number($('#pointsInput').value);const {error}=await supabase.from('positions').upsert({call_id:selectedCall.id,user_id:currentUser.id,side:selectedSide,points},{onConflict:'call_id,user_id'});if(error)return toast(error.message);$('#positionModal').close();toast(`${selectedSide} recorded with ${points} play points.`);await loadData();if($('#callDetailModal').open)openCall(selectedCall.id,false)});
$('#commentForm').addEventListener('submit',async e=>{e.preventDefault();if(!requireAccount())return;const body=$('#commentInput').value.trim();if(!body)return;const {error}=await supabase.from('call_comments').insert({call_id:selectedCall.id,author_id:currentUser.id,body});if(error)return toast(error.message);$('#commentInput').value='';await loadComments(selectedCall.id)});
$('#flagCallBtn').addEventListener('click',()=>{if(requireAccount())openModal('flagModal')});$('#flagForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.from('call_flags').insert({call_id:selectedCall.id,user_id:currentUser.id,reason:$('#flagReason').value.trim()});if(error)return toast(error.message);e.target.reset();$('#flagModal').close();toast('Wording flag recorded.')});
$('#adminResolveBtn').addEventListener('click',()=>openModal('resolveModal'));$('#resolveForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await supabase.rpc('resolve_call',{p_call_id:selectedCall.id,p_outcome:$('#resolveOutcome').value,p_note:$('#resolveNote').value.trim(),p_source_url:$('#resolveSourceUrl').value.trim()||null});if(error)return toast(error.message);e.target.reset();$('#resolveModal').close();toast('Permanent result recorded.');await loadData();await openCall(selectedCall.id,false)});
$('#shareCallBtn').addEventListener('click',async()=>{const u=`${location.origin}${location.pathname}#call-${selectedCall.id}`;await navigator.clipboard.writeText(u);toast('Call link copied.')});
$('#sortCalls').addEventListener('change',renderCalls);
document.addEventListener('click',e=>{const side=e.target.closest('[data-side]');if(side)return positionClick(side);const profile=e.target.closest('[data-profile]');if(profile){e.stopPropagation();return openProfile(profile.dataset.profile)}const call=e.target.closest('[data-open-call]');if(call)return openCall(call.dataset.openCall);const ch=e.target.closest('[data-channel]');if(ch)return setChannel(ch.dataset.channel)});
window.addEventListener('hashchange',handleHash);
boot();
