-- Called it. Phase 3 migration
-- Run ONCE in Supabase > SQL Editor > New query AFTER Phase 2 is already installed.

-- 1) Extend calls with explicit resolution metadata.
alter table public.calls add column if not exists resolution_method text not null default 'source';
alter table public.calls add column if not exists source_name text;
alter table public.calls add column if not exists resolution_note text;
alter table public.calls add column if not exists resolution_source_url text;

-- Keep methods limited to the three tiers in the concept brief.
do $$ begin
  alter table public.calls add constraint calls_resolution_method_check check (resolution_method in ('machine','source','jury'));
exception when duplicate_object then null; end $$;

-- 2) Discussion under individual calls.
create table if not exists public.call_comments (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.calls(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1200),
  created_at timestamptz not null default now()
);
create index if not exists call_comments_call_idx on public.call_comments(call_id, created_at);
alter table public.call_comments enable row level security;
drop policy if exists "comments public read" on public.call_comments;
create policy "comments public read" on public.call_comments for select using (true);
drop policy if exists "member creates own comments" on public.call_comments;
create policy "member creates own comments" on public.call_comments for insert to authenticated with check (auth.uid() = author_id);
grant select on public.call_comments to anon, authenticated;
grant insert on public.call_comments to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- 3) Admin list. Nothing is exposed to normal browsers except a yes/no admin check.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$ select exists(select 1 from public.admin_users where user_id = auth.uid()); $$;
grant execute on function public.is_admin() to authenticated;

-- 4) Automatically promote challenge calls whose 24 hours have elapsed.
create or replace function public.open_due_calls()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare n integer;
begin
  update public.calls set status='open'
  where status='challenge' and challenge_ends_at <= now();
  get diagnostics n = row_count;
  return n;
end;
$$;
grant execute on function public.open_due_calls() to anon, authenticated;

-- 5) Permanent admin-only settlement function.
create or replace function public.resolve_call(
  p_call_id bigint,
  p_outcome text,
  p_note text,
  p_source_url text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists(select 1 from public.admin_users where user_id = auth.uid()) then
    raise exception 'admin only';
  end if;
  if p_outcome not in ('YES','NO','VOID') then raise exception 'invalid outcome'; end if;
  if char_length(coalesce(p_note,'')) < 3 then raise exception 'resolution note required'; end if;

  if p_outcome='VOID' then
    update public.calls set status='void', result=null, resolved_at=now(), resolution_note=p_note, resolution_source_url=p_source_url where id=p_call_id;
  else
    update public.calls set status='resolved', result=(p_outcome='YES'), resolved_at=now(), resolution_note=p_note, resolution_source_url=p_source_url where id=p_call_id;
  end if;
end;
$$;
grant execute on function public.resolve_call(bigint,text,text,text) to authenticated;

-- 6) Existing positions may only be created/changed while the call is actually open.
drop policy if exists "member creates own positions" on public.positions;
create policy "member creates own positions" on public.positions for insert to authenticated
with check (auth.uid() = user_id and exists(select 1 from public.calls c where c.id=call_id and c.status='open'));
drop policy if exists "member updates own positions" on public.positions;
create policy "member updates own positions" on public.positions for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id and exists(select 1 from public.calls c where c.id=call_id and c.status='open'));

-- 7) Allow authenticated members to read total wording flags, but not alter others' flags.
-- We expose only a count through a function, not the private reasons.
create or replace function public.call_flag_count(p_call_id bigint)
returns integer
language sql
stable
security definer
set search_path = public
as $$ select count(*)::integer from public.call_flags where call_id=p_call_id; $$;
grant execute on function public.call_flag_count(bigint) to anon, authenticated;

-- OPTIONAL: make your current account an admin for manual resolutions during development.
-- Replace the email below, then run ONLY that insert line separately.
-- insert into public.admin_users(user_id)
-- select id from auth.users where email='YOUR_EMAIL_HERE'
-- on conflict do nothing;
