-- Called it. Phase 2 database schema
-- Run this whole file once in Supabase > SQL Editor > New query.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (username ~ '^[A-Za-z0-9_]{3,24}$'),
  created_at timestamptz not null default now()
);

create table if not exists public.calls (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  channel text not null check (channel in ('Markets','Tech','Crypto','World','Gadgets')),
  claim text not null check (char_length(claim) between 10 and 180),
  settlement_condition text not null check (char_length(settlement_condition) between 15 and 260),
  confidence smallint not null check (confidence between 50 and 99),
  resolution_date date not null check (resolution_date >= current_date),
  position_disclosure text check (position_disclosure is null or char_length(position_disclosure) <= 140),
  status text not null default 'challenge' check (status in ('challenge','open','resolved','void')),
  challenge_ends_at timestamptz not null default (now() + interval '24 hours'),
  result boolean,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint resolved_has_result check ((status <> 'resolved') or result is not null)
);

create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.calls(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  side text not null check (side in ('YES','NO')),
  points integer not null check (points between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(call_id,user_id)
);

create table if not exists public.threads (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  channel text not null check (channel in ('Markets','Tech','Crypto','World','Gadgets')),
  title text not null check (char_length(title) between 4 and 120),
  body text not null check (char_length(body) between 1 and 1800),
  created_at timestamptz not null default now()
);

create table if not exists public.call_flags (
  id bigint generated by default as identity primary key,
  call_id bigint not null references public.calls(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (char_length(reason) between 3 and 240),
  created_at timestamptz not null default now(),
  unique(call_id,user_id)
);

create index if not exists calls_created_idx on public.calls(created_at desc);
create index if not exists calls_resolution_idx on public.calls(resolution_date);
create index if not exists calls_channel_idx on public.calls(channel);
create index if not exists positions_call_idx on public.positions(call_id);
create index if not exists threads_created_idx on public.threads(created_at desc);

-- New auth users automatically receive a public profile.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  wanted text;
begin
  wanted := coalesce(new.raw_user_meta_data->>'username', split_part(new.email,'@',1));
  wanted := regexp_replace(wanted, '[^A-Za-z0-9_]', '', 'g');
  if char_length(wanted) < 3 then wanted := 'member_' || substr(new.id::text,1,8); end if;
  if exists(select 1 from public.profiles where username = wanted) then
    wanted := left(wanted,15) || '_' || substr(new.id::text,1,6);
  end if;
  insert into public.profiles(id,username) values(new.id,wanted);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Keep updated_at useful on changed positions.
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists positions_touch on public.positions;
create trigger positions_touch before update on public.positions for each row execute procedure public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.calls enable row level security;
alter table public.positions enable row level security;
alter table public.threads enable row level security;
alter table public.call_flags enable row level security;

-- Public reading: the product is built around public records.
drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read" on public.profiles for select using (true);
drop policy if exists "calls public read" on public.calls;
create policy "calls public read" on public.calls for select using (true);
drop policy if exists "positions public read" on public.positions;
create policy "positions public read" on public.positions for select using (true);
drop policy if exists "threads public read" on public.threads;
create policy "threads public read" on public.threads for select using (true);

-- Members can edit only their own profile.
drop policy if exists "profile owner update" on public.profiles;
create policy "profile owner update" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Calls can be created by the signed-in author. Resolution is intentionally not exposed to browsers yet.
drop policy if exists "member creates own calls" on public.calls;
create policy "member creates own calls" on public.calls for insert to authenticated with check (auth.uid() = author_id);

-- Positions: one per member per call, editable while call is open/challenge.
drop policy if exists "member creates own positions" on public.positions;
create policy "member creates own positions" on public.positions for insert to authenticated
with check (auth.uid() = user_id and exists(select 1 from public.calls c where c.id=call_id and c.status in ('challenge','open')));
drop policy if exists "member updates own positions" on public.positions;
create policy "member updates own positions" on public.positions for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id and exists(select 1 from public.calls c where c.id=call_id and c.status in ('challenge','open')));

-- Ordinary discussion.
drop policy if exists "member creates own threads" on public.threads;
create policy "member creates own threads" on public.threads for insert to authenticated with check (auth.uid() = author_id);

-- Wording flags are private to authenticated users for now.
drop policy if exists "member reads own flags" on public.call_flags;
create policy "member reads own flags" on public.call_flags for select to authenticated using (auth.uid() = user_id);
drop policy if exists "member creates own flag" on public.call_flags;
create policy "member creates own flag" on public.call_flags for insert to authenticated with check (auth.uid() = user_id);

-- Helpful grants (RLS still controls access).
grant usage on schema public to anon, authenticated;
grant select on public.profiles, public.calls, public.positions, public.threads to anon, authenticated;
grant update on public.profiles to authenticated;
grant insert on public.calls, public.positions, public.threads, public.call_flags to authenticated;
grant update on public.positions to authenticated;
grant select on public.call_flags to authenticated;
grant usage, select on all sequences in schema public to authenticated;
